<a href="https://colab.research.google.com/github/fanurs/pytorch-notes/blob/main/notes/tut02_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ❗_This tutorial uses GPU runtime._

# PyTorch tensors

If you are familiar with NumPy arrays, then PyTorch tensors are going to be very easy to learn. In this tutorial, we will use "arrays" to refer any NumPy arrays, and "tensors" to refer any PyTorch tensors.

In [1]:
import numpy as np
import torch as th

## Create an array / a tensor

In [2]:
x = np.array([2, 3, 5])
y = th.tensor([2, 3, 5])
display(x, y)

array([2, 3, 5])

tensor([2, 3, 5])

## Creating a tensor from an array

In [3]:
x = np.array([0.5, 0.25, 0.125])
th.from_numpy(x)

tensor([0.5000, 0.2500, 0.1250], dtype=torch.float64)

## Converting a tensor into an array

In [4]:
y = th.tensor([3.1, 3.14, 3.141])
y.numpy()

array([3.1  , 3.14 , 3.141], dtype=float32)

## Slicing

Slicing of PyTorch tensors is the same as in NumPy arrays.

In [5]:
x = np.array([1, 10, 100, 1000])
y = th.tensor([1, 10, 100, 1000])
display(x[2:], y[2:])

array([ 100, 1000])

tensor([ 100, 1000])

# Tensors on CPU and GPU

A tensor can either live in a CPU or GPU. Use the function `to()` to assign device, and `get_device()` to query the device that is being used.

In [6]:
y = th.tensor([1.1, 2.22, 3.333])
device = 'cuda' if th.cuda.is_available() else 'cpu'
y = y.to(device)
y.get_device()

0

If you are using GPU runtime, you should see `y.get_device()` returns `0`. If you are using CPU runtime, you should see `-1`.

If there are more than one GPU, you can specify the GPUs by `'cuda:0'`, `'cuda:1'`, and so on.

When using GPU runtime, it is possible to store tensors on different processing units.

In [7]:
y_cpu = th.tensor([1, 3, 5], device='cpu')
y_gpu = th.tensor([2, 4, 6], device='cuda')
display(y_cpu.get_device(), y_gpu.get_device())

-1

0

But we cannot perform operation between tensors from different processing units. The code cell below should give a `RuntimeError`:

In [8]:
y_cpu + y_gpu

RuntimeError: ignored

# Important differences between NumPy arrays and PyTorch tensors

We are not going to go through all the functions that `pytorch.Tensor` supports. For that, you can always refer to the documentation page at https://pytorch.org/docs/stable/tensors.html. Instead, it is more interesting to talk about a few noteworthy distinctions between NumPy arrays and PyTorch tensors.

## Default data type

In NumPy, the default data type is `float64`. In PyTorch, the default data type is `float32`.

In [9]:
display(np.array([]).dtype)
display(th.tensor([]).dtype)

dtype('float64')

torch.float32

## Random module

In NumPy, we need the submodule [`numpy.random`](https://numpy.org/doc/stable/reference/random/index.html) to generate random numbers. In PyTorch, there is no submodule.

In [10]:
np.random.seed(0)
th.manual_seed(0)

In [11]:
display(np.random.rand(2))
display(th.rand(2))

array([0.5488135 , 0.71518937])

tensor([0.4963, 0.7682])

# References

- https://pytorch.org/docs/stable/tensors.html
- https://pytorch.org/docs/stable/cuda.html